# Generated by Django 4.0.2 on 2022-03-12 10:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_name', models.CharField(max_length=200)),
                ('address', models.CharField(max_length=200)),
                ('phone', models.CharField(max_length=200)),
                ('pan_no', models.CharField(max_length=200)),
                ('invoice_no', models.CharField(max_length=200, unique=True)),
                ('invoice_date', models.DateField()),
                ('payment_mode', models.CharField(choices=[('1', 'Cash'), ('2', 'Credit'), ('3', 'Card')], max_length=50)),
                ('subtotal', models.DecimalField(decimal_places=2, default=0, max_digits=20)),
                ('discount', models.DecimalField(decimal_places=2, max_digits=20)),
                ('taxable_amount', models.DecimalField(decimal_places=2, default=0, max_digits=20)),
                ('vat', models.DecimalField(decimal_places=2, max_digits=20)),
                ('total_amount', models.DecimalField(decimal_places=2, default=0, max_digits=20)),
                ('in_words', models.CharField(blank=True, max_length=500, null=True)),
                ('remarks', models.CharField(blank=True, max_length=500, null=True)),
                ('received_by', models.CharField(blank=True, max_length=200, null=True)),
                ('prepared_by', models.CharField(max_length=200)),
                ('authorized_sign', models.CharField(blank=True, max_length=200, null=True)),
                ('date_time', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Ledger',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('c_name', models.CharField(max_length=500, null=True)),
                ('c_code', models.CharField(blank=True, max_length=200, null=True)),
                ('c_date_form_start', models.DateField(blank=True, null=True)),
                ('c_date_form_end', models.DateField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ledger_description',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('c_description', models.CharField(blank=True, max_length=200, null=True)),
                ('c_current_date', models.DateField(blank=True, default='-', null=True)),
                ('c_debt_amt', models.FloatField(default='0', null=True)),
                ('c_credit_amt', models.FloatField(default='0', null=True)),
                ('ledgerDetail', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounting.ledger')),
            ],
        ),
        migrations.CreateModel(
            name='Bill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_no', models.CharField(max_length=10)),
                ('particular', models.CharField(max_length=200)),
                ('alt_qty', models.IntegerField(default=0)),
                ('quantity', models.IntegerField()),
                ('Uom', models.CharField(blank=True, max_length=100, null=True)),
                ('rate', models.DecimalField(decimal_places=2, max_digits=20)),
                ('discount', models.DecimalField(decimal_places=2, default=0, max_digits=20)),
                ('amount', models.DecimalField(decimal_places=2, default=0, max_digits=20)),
                ('invoice_no', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invoice', to='accounting.customer')),
            ],
        ),
    ]
