# Generated by Django 4.0.2 on 2022-03-12 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0002_alter_customer_invoice_no'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='invoice_no',
            field=models.CharField(max_length=200, unique=True),
        ),
    ]
