# Generated by Django 3.2.12 on 2022-02-28 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0003_auto_20220228_1308'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ledgerdetail',
            name='c_FY',
        ),
        migrations.AddField(
            model_name='ledgerdetail',
            name='c_FY_end',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='ledgerdetail',
            name='c_FY_start',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='ledgerdetail',
            name='c_credit_amt',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='ledgerdetail',
            name='c_current_date',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='ledgerdetail',
            name='c_date_form_end',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='ledgerdetail',
            name='c_date_form_start',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='ledgerdetail',
            name='c_debt_amt',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='ledgerdetail',
            name='c_name',
            field=models.CharField(max_length=500, null=True),
        ),
    ]
