# Generated by Django 3.2.12 on 2022-02-28 07:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0005_auto_20220228_1331'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ledger_descriptio',
            new_name='ledger_description',
        ),
    ]
