# Generated by Django 3.2.12 on 2022-02-28 07:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0007_auto_20220228_1339'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ledger_description',
            old_name='ledgerdetail',
            new_name='ledger_detail',
        ),
    ]
