# Generated by Django 3.2.12 on 2022-02-28 08:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0008_rename_ledgerdetail_ledger_description_ledger_detail'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ledger_description',
            old_name='ledger_detail',
            new_name='ledgerDetail',
        ),
    ]
