# Generated by Django 3.2.12 on 2022-02-28 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0010_auto_20220228_1601'),
    ]

    operations = [
        migrations.AddField(
            model_name='ledger',
            name='date_create',
            field=models.DateField(auto_now_add=True, null=True),
        ),
    ]
