# Generated by Django 3.2.12 on 2022-02-28 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0012_ledger_description_ledgerdetail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ledger_description',
            name='c_credit_amt',
            field=models.FloatField(default='0', null=True),
        ),
        migrations.AlterField(
            model_name='ledger_description',
            name='c_current_date',
            field=models.DateField(blank=True, default='', null=True),
        ),
        migrations.AlterField(
            model_name='ledger_description',
            name='c_debt_amt',
            field=models.FloatField(default='0', null=True),
        ),
        migrations.DeleteModel(
            name='ledger',
        ),
    ]
