# Generated by Django 3.2.12 on 2022-03-01 12:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0013_auto_20220228_1822'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ledgerDetail',
            new_name='Ledger',
        ),
    ]
