# Generated by Django 4.0.2 on 2022-03-03 06:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0013_auto_20220228_1822'),
    ]

    operations = [
        migrations.CreateModel(
            name='customer_bill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_name', models.CharField(max_length=200)),
                ('address', models.CharField(max_length=200)),
                ('phone', models.CharField(max_length=200, null=True)),
                ('pan_no', models.CharField(max_length=200, null=True)),
                ('invoice_no', models.CharField(max_length=200, unique=True)),
                ('invoice_date', models.DateField()),
                ('payment_mode', models.CharField(choices=[('1', 'Cash'), ('2', 'Credit'), ('3', 'Card')], max_length=50)),
                ('subtotal', models.DecimalField(decimal_places=2, default=0, max_digits=20)),
                ('discount', models.DecimalField(decimal_places=2, default=0, max_digits=20)),
                ('vat', models.DecimalField(decimal_places=2, default=0, max_digits=20)),
                ('total_amount', models.DecimalField(decimal_places=2, default=0, max_digits=20)),
                ('received_by', models.CharField(max_length=200, null=True)),
                ('prepared_by', models.CharField(max_length=200, null=True)),
                ('authorized_sign', models.CharField(max_length=200, null=True)),
                ('date_time', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='bill_item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_no', models.CharField(max_length=10)),
                ('particular', models.CharField(max_length=200)),
                ('quantity', models.IntegerField()),
                ('Uom', models.CharField(max_length=100)),
                ('rate', models.DecimalField(decimal_places=2, default=0, max_digits=20)),
                ('discount', models.DecimalField(decimal_places=2, default=0, max_digits=20)),
                ('amount', models.DecimalField(decimal_places=2, default=0, max_digits=20)),
                ('invoice_no', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounting.customer_bill')),
            ],
        ),
    ]
