# Generated by Django 4.0.2 on 2022-03-03 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0014_customer_bill_bill_item'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer_bill',
            name='in_words',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='customer_bill',
            name='remarks',
            field=models.CharField(max_length=500, null=True),
        ),
    ]
