# Generated by Django 3.2.12 on 2022-03-02 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0014_rename_ledgerdetail_ledger'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ledger_description',
            name='c_description',
            field=models.CharField(default='Empty', max_length=200, null=True),
        ),
    ]
