# Generated by Django 3.2.12 on 2022-03-02 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0015_alter_ledger_description_c_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ledger_description',
            name='c_description',
            field=models.CharField(blank='', max_length=200, null=True),
        ),
    ]
