# Generated by Django 4.0.2 on 2022-03-03 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0015_customer_bill_in_words_customer_bill_remarks'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer_bill',
            name='taxable_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=20),
        ),
        migrations.AlterField(
            model_name='customer_bill',
            name='authorized_sign',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='customer_bill',
            name='date_time',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='customer_bill',
            name='in_words',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='customer_bill',
            name='pan_no',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='customer_bill',
            name='phone',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='customer_bill',
            name='remarks',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
