# Generated by Django 4.0.2 on 2022-03-03 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0016_customer_bill_taxable_amount_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer_bill',
            name='address',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
