# Generated by Django 3.2.12 on 2022-03-02 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0016_alter_ledger_description_c_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ledger_description',
            name='c_current_date',
            field=models.DateField(blank=True, default='-', null=True),
        ),
    ]
