# Generated by Django 3.2.12 on 2022-03-02 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0017_alter_ledger_description_c_current_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ledger_description',
            name='c_description',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
