# Generated by Django 4.0.2 on 2022-03-03 14:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0017_alter_customer_bill_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bill_item',
            name='invoice_no',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invoice', to='accounting.customer_bill'),
        ),
    ]
