# Generated by Django 4.0.2 on 2022-03-04 07:52

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0018_alter_bill_item_invoice_no'),
    ]

    operations = [
        migrations.AddField(
            model_name='bill_item',
            name='alt_qty',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
