# Generated by Django 4.0.2 on 2022-03-04 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0019_bill_item_alt_qty'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer_bill',
            name='received_by',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
