# Generated by Django 3.2.12 on 2022-03-04 16:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0018_alter_ledger_description_c_description'),
        ('accounting', '0021_alter_bill_item_uom_alter_bill_item_alt_qty_and_more'),
    ]

    operations = [
    ]
